version: "1"

services:

  stats-server:
    container_name: stats-server
    depends_on:
      - stats-db
    ports:
      - "${STAT_PORT}:${STAT_PORT}"
    build: ewm-statistic/statistic-server/.
    environment:
      - STAT_PORT=${STAT_PORT}
      - STAT_DB_PORT=${STAT_DB_PORT}
      - STAT_DB_NAME=${STAT_DB_NAME}
      - STAT_DB_LOGIN=${STAT_DB_LOGIN}
      - STAT_DB_PASSWORD=${STAT_DB_PASSWORD}

  stats-db:
    container_name: stats-db
    image: postgres:14-alpine
    ports:
      - "${STAT_DB_PORT}:5432"
    environment:
      - POSTGRES_DB=${STAT_DB_NAME}
      - POSTGRES_USER=${STAT_DB_LOGIN}
      - POSTGRES_PASSWORD=${STAT_DB_PASSWORD}