create table if not exists users (
	id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	user_name VARCHAR(255) not null,
	email VARCHAR(255) NOT NULL,
	CONSTRAINT pk_user PRIMARY KEY (id),
	CONSTRAINT UQ_USER_NAME UNIQUE (user_name),
	CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

create table if not exists categories (
	id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	category_name VARCHAR(255) not null,
	CONSTRAINT pk_category PRIMARY KEY (id),
	CONSTRAINT UQ_category_name UNIQUE (category_name)
);

create table if not exists events (
	id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	annotation VARCHAR(2000),
	title VARCHAR(120) NOT NULL,
	description VARCHAR(7000),
    lattitude FLOAT,
    longtitude FLOAT,
    participant_limit BIGINT NOT NULL,
    paid BOOLEAN NOT NULL,
    sended BOOLEAN NOT NULL,
    moderation BOOLEAN NOT NULL,
    statement VARCHAR(32),
    event_date TIMESTAMP WITHOUT TIME zone NOT NULL,
    creation_time TIMESTAMP WITHOUT TIME zone NOT NULL,
    publication_time TIMESTAMP WITHOUT TIME zone, -- May be null? some logic on it
    initiator_id BIGINT REFERENCES users (id) NOT NULL,
    category_id BIGINT REFERENCES categories (id) NOT NULL,
	CONSTRAINT pk_event PRIMARY KEY (id)
);

create table if not exists participations (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    requester_id BIGINT REFERENCES users (id) NOT NULL,
    event_id BIGINT REFERENCES events (id) NOT NULL,
    status VARCHAR(32) NOT NULL,
    creation_time TIMESTAMP WITHOUT TIME zone,
    CONSTRAINT pk_participation PRIMARY KEY (id)
);

create table if not exists compilations (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned BOOLEAN NOT NULL,
    title VARCHAR(500) NOT NULL,
    CONSTRAINT pk_compilations PRIMARY KEY (id),
    CONSTRAINT uq_compilation_name UNIQUE (title)
);

create table if not exists compilation_events (
    compilation_id BIGINT REFERENCES compilations (id) NOT NULL,
    event_id BIGINT REFERENCES events (id) NOT NULL,
    PRIMARY KEY (compilation_id, event_id)
);

create table if not exists user_liked_event (
    event_id BIGINT REFERENCES events (id) NOT NULL,
    liker_id BIGINT REFERENCES users (id) NOT NULL,
    CONSTRAINT uq_likes UNIQUE (event_id, liker_id)
);

create or replace view events_calc as
select e.*, coalesce(ule.likes, 0) as likes, coalesce(rq.confirmedRequests, 0) as confirmedRequests
from events e
left join (
	select event_id, count(*) as likes from public.user_liked_event group by event_id) ule
	on ule.event_id =e.id
left join (
	select event_id, count(*) as confirmedRequests from participations p where p.status = 'CONFIRMED' group by event_id) rq
	on rq.event_id =e.id;