create table if not exists users (
	id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	user_name VARCHAR(255) not null,
	email VARCHAR(255) NOT NULL,
	CONSTRAINT pk_user PRIMARY KEY (id),
	CONSTRAINT UQ_USER_NAME UNIQUE (user_name),
	CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

create table if not exists categories (
	id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	category_name VARCHAR(255) not null,
	CONSTRAINT pk_category PRIMARY KEY (id),
	CONSTRAINT UQ_category_name UNIQUE (category_name)
);

create table if not exists events (
	id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	annotation VARCHAR(2000),
	title VARCHAR(120) NOT NULL,
	description VARCHAR(7000),
    lattitude FLOAT,
    longtitude FLOAT,
    participant_limit BIGINT,
    paid BOOLEAN,
    sended BOOLEAN,
    moderation BOOLEAN,
    statement VARCHAR(32),
    event_date TIMESTAMP WITHOUT TIME zone,
    creation_time TIMESTAMP WITHOUT TIME zone,
    publication_time TIMESTAMP WITHOUT TIME zone,
    initiator_id BIGINT REFERENCES users (id),
    category_id BIGINT REFERENCES categories (id),
	CONSTRAINT pk_event PRIMARY KEY (id)
);

create table if not exists participations (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    requester_id BIGINT REFERENCES users (id),
    event_id BIGINT REFERENCES events (id),
    status VARCHAR(32),
    creation_time TIMESTAMP WITHOUT TIME zone,
    CONSTRAINT pk_participation PRIMARY KEY (id)
);

create table if not exists compilations (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned BOOLEAN,
    title VARCHAR(500) NOT NULL,
    CONSTRAINT pk_compilations PRIMARY KEY (id),
    CONSTRAINT uq_compilation_name UNIQUE (title)
);

create table if not exists compilation_events (
    compilation_id BIGINT REFERENCES compilations (id),
    event_id BIGINT REFERENCES events (id),
    PRIMARY KEY (compilation_id, event_id)
);