create table if not exists users (
	id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	user_name VARCHAR(255) not null,
	email VARCHAR(255) NOT NULL,
	CONSTRAINT pk_user PRIMARY KEY (id),
	CONSTRAINT UQ_USER_NAME UNIQUE (user_name),
	CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);